# Global plugin settings.

colors:
  # Primary message style. Use {message}. Examples: <gradient:#fa3cda:#ffffff>{message}</gradient> or <#fa3cda>{message}</#ffffff>.
  Prime-Colors-One: "<#fa3cda>{message}</#ffffff>"

  # Secondary message style. Same color formats as above.
  Prime-Colors-Two: "<#ffffff>{message}</#1cd9eb>"

  features:
    # Enables MiniMessage tags and hex colors.
    mini-message: true

    # Enables legacy & color codes.
    legacy-colors: true


update:
  # Enables version checks and update downloads.
  enabled: true

  # Checks for updates once per day.
  auto-update: false


# Database settings for DB-based systems like Sync Items.
DB:
  # Enables database systems.
  enabled: false

  # Supported: mysql, mariadb.
  type: mysql

  # Host/domain with port.
  address: "127.0.0.1:3306"

  # DB name.
  database: "mrsvensf"

  # DB user.
  username: "root"

  # DB password.
  password: ""
