# Paper plugin descriptor.

# Plugin name shown by the server.
name: MrSvenSF

# Filled from pom.xml during Maven build.
version: '${project.version}'

# Plugin main class.
main: DE.MrSvenSF.mrsvensf.MrSvenSF

# Paper/Bukkit API version.
api-version: '1.21'

# Plugin author.
authors: [ MrSvenSF ]

# Plugin website.
website: mrsvensf.com

# Optional integrations.
softdepend: [ PlaceholderAPI, LuckPerms ]

# Permission metadata.
permissions:
  # Allows config reload.
  mrsvensf.admin.reload:
    default: op

  # Allows version checks.
  mrsvensf.admin.version:
    default: op

  # Allows manual updates.
  mrsvensf.admin.update:
    default: op

  # Allows setting spawn.
  mrsvensf.admin.setspawn:
    default: op

  # Allows spawn teleport.
  mrsvensf.player.spawn:
    default: true
