name: MrSvenSF
version: 'v0.1'
main: DE.MrSvenSF.mrsvensf.MrSvenSF
api-version: '1.21'
authors: [ MrSvenSF ]
website: mrsvensf.com
softdepend: [ PlaceholderAPI, LuckPerms ]
commands:
  mrsvensf:
    description: Main command for mrsvensf plugin
    usage: /mrsvensf <reload|version|update|setspawn>
  spawn:
    description: Teleport to configured spawn
    usage: /spawn
permissions:
  mrsvensf.admin.use:
    description: Allows using /mrsvensf command
    default: op
  mrsvensf.admin.reload:
    description: Allows reloading all mrsvensf configs
    default: op
  mrsvensf.admin.version:
    description: Allows checking current and latest plugin version
    default: op
  mrsvensf.admin.update:
    description: Allows downloading plugin updates
    default: op
  mrsvensf.admin.setspawn:
    description: Allows setting the spawn position
    default: op
  mrsvensf.player.spawn:
    description: Allows using /spawn
    default: true
